version: '3'
services:
  db:
    image: mariadb
    container_name: "mariadbtest2"
    stop_grace_period: 30s
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_CHARACTER_SET_SERVER: 'utf8mb4'
        MYSQL_COLLATION_SERVER: 'utf8mb4_unicode_ci'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    
    volumes:
       - ./.docker/mariadb-init.d:/docker-entrypoint-initdb.d
       - ./.docker/mariadb-dumps:/mariadb-dumps
       - my-db:/var/lib/mysql

volumes:
  my-db:
